### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by Mi12Mi12Cu** [renatocan/rp-generative-adversarial-networks#1]
Hello. Does anyone else experience this error when implementing tutorial on handwriting generation? How do i resolve this?

![image](https://user-images.githubusercontent.com/82485291/120252002-32653380-c2be-11eb-88da-1d9f0673aa4e.png)

**Comment by renatocan** [comment]
Have you created the conda environment using the `conda_env.yml` file?

**Comment by Mi12Mi12Cu** [comment]
Did that and it worked, Thanks
