### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Storm-131** [renatocan/rp-generative-adversarial-networks#2]
Dear Mr. Candido,
thank you for your great tutorial. Can you tell me if this code is open source, can it be modified and versions of it uploaded into another public repo (with a reference to your code)? I would appreciate it if you could add a license to your code. :)
Best wishes,
Tom

**Comment by renatocan** [comment]
Sure! Feel free to use it. Just add a reference to the original repo and indicate if you make any change, please.

Best,

Renato.

**Comment by renatocan** [comment]
I have added the GPL license.
